### PR TITLE
Update WeatherProvider documentation

### PR DESCRIPTION
**Pull request by rejas**
After reworking the unit handling in https://github.com/MichMich/MagicMirror/pull/2849 we need to update the docs

### CODE REVIEW

**Review by khassel — APPROVED** [review]

**Comment by rejas** [comment]
This would have to be merged now since the changes are already released in the current MM version @khassel

**Comment by rejas** [comment]
Thx. Should we do the "squahs&merge" tactic here too btw?

**Comment by khassel** [comment]
from my side, yes.

There are now still 3 PR's open all with conflicts in weather.md, can you take a look into this?

**Comment by rejas** [comment]
> There are now still 3 PR's open all with conflicts in weather.md, can you take a look into this?

Already on it ;-)

**Pull request merged**
