### PR TITLE
Remove vendor and font part for Windows

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
I haven't tested it, but `postinstall` should take care of this by now.

### CODE REVIEW

**Comment by rejas** [comment]
My Windows 11 doesnt like the prepare script and fails during install... Will have to investigate someday...

**Comment by rejas** [comment]
Maybe merged a little too early @MichMich or did you test it?

**Comment by MichMich** [comment]
Ohhwww. dang it. Messed it up. Was confused with an other PR (even worse: an other repo). Sorry! Shall I revert it?

Note to self: don't open to many GitHub tabs.

**Comment by rejas** [comment]
Reverting might be the right option at the moment.

**Comment by MichMich** [comment]
Reverted.

**Pull request merged**
