### PR TITLE
Allow `npm run local:dev` for local develop (without https)

### PR DESCRIPTION
**Pull request by bugsounet**
For local develop and don't check https
it will use http only

### CODE REVIEW

**Comment by bugsounet** [comment]
`npm start` or `npm run docs:dev` show error:

```js
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

For develop and just see result content in local:  https is not require
So i create `npm run local:dev` and works ;)

**Comment by rejas** [comment]
What node version are you using?

**Comment by bugsounet** [comment]
v18.16.1

Why?

**Comment by bugsounet** [comment]
I just test with debian 11 desktop and it works without this path

Maybe it's related with `ubuntu` OS. 

This patch is not really required but only useful in my case
So, it's up to you, this can help (in my case)

**Comment by rejas** [comment]
I had this kind of error too and most of the time (found it on the net), deleting node_modules helped sovle it.

**Comment by bugsounet** [comment]
by deleting node_modules, it still not work

**Comment by bugsounet** [comment]
This seems to be fixed on ubuntu 23.10

@rejas: Do you want to push it anyway or should I close this PR?

**Comment by rejas** [comment]
Please close it.

**Pull request closed without merging**
