### PR TITLE
Add info on how to run MM on other OS

### PR DESCRIPTION
**Pull request by rejas**
... like windows

Makes https://github.com/MichMich/MagicMirror/pull/2698 irrelevant

### CODE REVIEW

**Comment by khassel** [comment]
AFAIK the section `Common Installation Issues` is not common but a windows workaround. So I would move this under the new windows section.

**Comment by rejas** [comment]
Move that info into the windows section.

**Comment by khassel** [comment]
sorry @rejas for not being clear enough.

AFAIK for getting started with windows you have to remove the DISPLAY stuff **and** do the manual installation in the `vendor` directory. So there would be nothing left in the "Common Installation Issues".

**Comment by rejas** [comment]
Thanks for the help, updated my PR accordinlgy.

**Review by khassel — APPROVED** [review]

**Pull request merged**
