### PR TITLE
Update customcss.md

### PR DESCRIPTION
**Pull request by rico24**
New link to the Clock module, the old one isn't working anymore.

### CODE REVIEW

**Comment by rico24** [comment]
Just curious; I have made my first pull request here. Are there some next steps I have to do before this change is approved?

**Comment by rico24** [comment]
Just curious; I have made my first pull request here. Are there some next steps I have to do before this change is approved?

**Comment by rejas** [comment]
I think @MichMich only merges the doc PRs when a new MM version is released (next one would be on first of july). so probably you just have to wait 10 more days ;-)

**Comment by rico24** [comment]
No problem, as I mentioned just curious because it was open for some time ;)

**Comment by MichMich** [comment]
I must admit I don't always check incoming PR's for this repo because it's usually release specific. So as said I will merge it whenever I release a new MagicMirror² version. 

If you mention me in a comment saying "hey, this isn't release specific" i might merge it right away.

**Pull request merged**
